export type SpeciesNFT = {
  scientificName?: string
  phylum?: string
  clazz?: string
  order?: string
  family?: string
  genus?: string
  threatStatus?: ThreatStatus
  kingdom?: Kingdom
  sex?: Sex
  image?: OccurrenceImage
  vernacularName?: VernacularName
  location?: OccurrenceLocation
  descriptions?: Description[]
  isOwned: boolean
}

export type OccurrenceImage = {
  id?: number
  url: string
  referenceUrl?: string
  title: string
  description?: string
  creator?: string
  createdAt?: string
  contributor?: string
  publisher?: string
  rightsHolder?: string
  source?: string
  license?: License
}

export type Description = {
  id?: number
  type?: string
  referenceUrl?: string
  title?: string
  description: string
  creator?: string
  contributor?: string
  source?: string
  language?: string
  license?: License
}

export type VernacularName = {
  id?: number
  VernacularName: string
  sex?: Sex
  language?: string
  country?: Country
  lifeStage?: LifeStage
}

export type OccurrenceLocation = {
  id?: number
  locationId: string
  locality: string
  locationRemarks?: string
  occurrenceStatus?: OccurrenceStatus
  threatStatus?: ThreatStatus
  establishmentMeans?: EstablishmentMeans
  country?: Country
  lifeStage?: LifeStage
}

export enum License {
  CC0_1_0,
  CC_BY_4_0,
  CC_BY_NC_4_0,
  UNSPECIFIED,
  UNSUPPORTED
}

export enum EstablishmentMeans {
  NATIVE = 'native',
  INTRODUCED = 'introduced',
  NATURALISED = 'naturalised',
  INVASIVE = 'invasive',
  MANAGED = 'managed',
  UNCERTAIN = 'uncertain'
}

export enum LifeStage {
  ZYGOTE,
  EMBRYO,
  LARVA,
  JUVENILE,
  ADULT,
  SPOROPHYTE,
  SPORE,
  GAMETOPHYTE,
  GAMETE,
  PUPA
}

export enum OccurrenceStatus {
  PRESENT = 'present',
  COMMON = 'common',
  RARE = 'rare',
  IRREGULAR = 'irregular',
  DOUBTFUL = 'doubtful',
  EXCLUDED = 'excluded',
  ABSENT = 'absent'
}

export const LICENSE_NAME = {
  [License.CC0_1_0]: 'Public Domain (CC0 1.0)',
  [License.CC_BY_4_0]: 'Creative Commons Attribution (CC-BY) 4.0',
  [License.CC_BY_NC_4_0]:
    'Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0',
  [License.UNSPECIFIED]: '',
  [License.UNSUPPORTED]: ''
}

export const LICENSE_URL = {
  [License.CC0_1_0]:
    'http://creativecommons.org/publicdomain/zero/1.0/legalcode',
  [License.CC_BY_4_0]: 'http://creativecommons.org/licenses/by/4.0/legalcode',
  [License.CC_BY_NC_4_0]:
    'http://creativecommons.org/licenses/by-nc/4.0/legalcode',
  [License.UNSPECIFIED]: '',
  [License.UNSUPPORTED]: ''
}

export enum ThreatStatus {
  EXTINCT = 'EX',
  EXTINCT_IN_THE_WILD = 'EW',
  REGIONALLY_EXTINCT = 'RE',
  CRITICALLY_ENDANGERED = 'CE',
  ENDANGERED = 'EN',
  VULNERABLE = 'VU',
  NEAR_THREATENED = 'NT',
  LEAST_CONCERN = 'LC',
  DATA_DEFICIENT = 'DD',
  NOT_APPLICABLE = 'NA',
  NOT_EVALUATED = 'NE'
}
export const THREATSTATUS_BACKGROUND_COLOR_LIGHT = {
  [ThreatStatus.EXTINCT]: '#412728',
  [ThreatStatus.EXTINCT_IN_THE_WILD]: '#B87C4C',
  [ThreatStatus.REGIONALLY_EXTINCT]: '#F9F871',
  [ThreatStatus.CRITICALLY_ENDANGERED]: '#FFBEC3',
  [ThreatStatus.ENDANGERED]: '#5F4A84',
  [ThreatStatus.VULNERABLE]: '#7B9926',
  [ThreatStatus.NEAR_THREATENED]: '#006666',
  [ThreatStatus.LEAST_CONCERN]: '#B4E073',
  [ThreatStatus.DATA_DEFICIENT]: '#DFC8DB',
  [ThreatStatus.NOT_APPLICABLE]: '#DFC8DB',
  [ThreatStatus.NOT_EVALUATED]: '#DFC8DB'
}
export const THREATSTATUS_BACKGROUND_COLOR = {
  [ThreatStatus.EXTINCT]: '#000000',
  [ThreatStatus.EXTINCT_IN_THE_WILD]: '#000000',
  [ThreatStatus.REGIONALLY_EXTINCT]: '#000000',
  [ThreatStatus.CRITICALLY_ENDANGERED]: '#cd3030',
  [ThreatStatus.ENDANGERED]: '#cd6630',
  [ThreatStatus.VULNERABLE]: '#cd9a00',
  [ThreatStatus.NEAR_THREATENED]: '#006666',
  [ThreatStatus.LEAST_CONCERN]: '#006666',
  [ThreatStatus.DATA_DEFICIENT]: '#c6c6c6',
  [ThreatStatus.NOT_APPLICABLE]: '#c6c6c6',
  [ThreatStatus.NOT_EVALUATED]: '#c6c6c6'
}
export const THREATSTATUS_COLOR = {
  [ThreatStatus.EXTINCT]: '#fff',
  [ThreatStatus.EXTINCT_IN_THE_WILD]: '#c33',
  [ThreatStatus.REGIONALLY_EXTINCT]: '#c33',
  [ThreatStatus.CRITICALLY_ENDANGERED]: '#fdc7c7',
  [ThreatStatus.ENDANGERED]: '#ffcd9a',
  [ThreatStatus.VULNERABLE]: '#ffffcd',
  [ThreatStatus.NEAR_THREATENED]: '#9acd9a',
  [ThreatStatus.LEAST_CONCERN]: '#fff',
  [ThreatStatus.DATA_DEFICIENT]: '#fff',
  [ThreatStatus.NOT_APPLICABLE]: '#fff',
  [ThreatStatus.NOT_EVALUATED]: '#fff'
}
export enum Kingdom {
  ANIMALIA = 'ANIMALIA',
  ARCHAEA = 'ARCHAEA',
  BACTERIA = 'BACTERIA',
  PLANTAE = 'PLANTAE',
  PROTOZOA = 'PROTOZOA',
  FUNGI = 'FUNGI',
  CHROMISTA = 'CHROMISTA',
  VIRUSES = 'VIRUSES'
}
export enum Sex {
  NONE = 'NONE',
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  HERMAPHRODITE = 'HERMAPHRODITE'
}
export enum Region {
  AFRICA = 'AFRICA',
  ASIA = 'ASIA',
  EUROPE = 'EUROPE',
  NORTH_AMERICA = 'NORTH_AMERICA',
  OCEANIA = 'OCEANIA',
  LATIN_AMERICA = 'LATIN_AMERICA',
  ANTARCTICA = 'ANTARCTICA'
}
export enum Country {
  AFGHANISTAN = 'AF',
  ALAND_ISLANDS = 'AX',
  ALBANIA = 'AL',
  ALGERIA = 'DZ',
  AMERICAN_SAMOA = 'AS',
  ANDORRA = 'AD',
  ANGOLA = 'AO',
  ANGUILLA = 'AI',
  ANTARCTICA = 'AQ',
  ANTIGUA_BARBUDA = 'AG',
  ARGENTINA = 'AR',
  ARMENIA = 'AM',
  ARUBA = 'AW',
  AUSTRALIA = 'AU',
  AUSTRIA = 'AT',
  AZERBAIJAN = 'AZ',
  BAHAMAS = 'BS',
  BAHRAIN = 'BH',
  BANGLADESH = 'BD',
  BARBADOS = 'BB',
  BELARUS = 'BY',
  BELGIUM = 'BE',
  BELIZE = 'BZ',
  BENIN = 'BJ',
  BERMUDA = 'BM',
  BHUTAN = 'BT',
  BOLIVIA = 'BO',
  BONAIRE_SINT_EUSTATIUS_SABA = 'BQ',
  BOSNIA_HERZEGOVINA = 'BA',
  BOTSWANA = 'BW',
  BOUVET_ISLAND = 'BV',
  BRAZIL = 'BR',
  BRITISH_INDIAN_OCEAN_TERRITORY = 'IO',
  BRUNEI_DARUSSALAM = 'BN',
  BULGARIA = 'BG',
  BURKINA_FASO = 'BF',
  BURUNDI = 'BI',
  CAMBODIA = 'KH',
  CAMEROON = 'CM',
  CANADA = 'CA',
  CAPE_VERDE = 'CV',
  CAYMAN_ISLANDS = 'KY',
  CENTRAL_AFRICAN_REPUBLIC = 'CF',
  CHAD = 'TD',
  CHILE = 'CL',
  CHINA = 'CN',
  CHRISTMAS_ISLAND = 'CX',
  COCOS_ISLANDS = 'CC',
  COLOMBIA = 'CO',
  COMOROS = 'KM',
  CONGO_DEMOCRATIC_REPUBLIC = 'CD',
  CONGO = 'CG',
  COOK_ISLANDS = 'CK',
  COSTA_RICA = 'CR',
  CÔTE_DIVOIRE = 'CI',
  CROATIA = 'HR',
  CUBA = 'CU',
  CURAÇAO = 'CW',
  CYPRUS = 'CY',
  CZECH_REPUBLIC = 'CZ',
  DENMARK = 'DK',
  DJIBOUTI = 'DJ',
  DOMINICA = 'DM',
  DOMINICAN_REPUBLIC = 'DO',
  ECUADOR = 'EC',
  EGYPT = 'EG',
  EL_SALVADOR = 'SV',
  EQUATORIAL_GUINEA = 'GQ',
  ERITREA = 'ER',
  ESTONIA = 'EE',
  ETHIOPIA = 'ET',
  FALKLAND_ISLANDS = 'FK',
  FAROE_ISLANDS = 'FO',
  FIJI = 'FJ',
  FINLAND = 'FI',
  FRANCE = 'FR',
  FRENCH_GUIANA = 'GF',
  FRENCH_POLYNESIA = 'PF',
  FRENCH_SOUTHERN_TERRITORIES = 'TF',
  GABON = 'GA',
  GAMBIA = 'GM',
  GEORGIA = 'GE',
  GERMANY = 'DE',
  GHANA = 'GH',
  GIBRALTAR = 'GI',
  GREECE = 'GR',
  GREENLAND = 'GL',
  GRENADA = 'GD',
  GUADELOUPE = 'GP',
  GUAM = 'GU',
  GUATEMALA = 'GT',
  GUERNSEY = 'GG',
  GUINEA = 'GN',
  GUINEA_BISSAU = 'GW',
  GUYANA = 'GY',
  HAITI = 'HT',
  HEARD_MCDONALD_ISLANDS = 'HM',
  VATICAN = 'VA',
  HONDURAS = 'HN',
  HONG_KONG = 'HK',
  HUNGARY = 'HU',
  ICELAND = 'IS',
  INDIA = 'IN',
  INDONESIA = 'ID',
  IRAN = 'IR',
  IRAQ = 'IQ',
  IRELAND = 'IE',
  ISLE_OF_MAN = 'IM',
  ISRAEL = 'IL',
  ITALY = 'IT',
  JAMAICA = 'JM',
  JAPAN = 'JP',
  JERSEY = 'JE',
  JORDAN = 'JO',
  KAZAKHSTAN = 'KZ',
  KENYA = 'KE',
  KIRIBATI = 'KI',
  KOREA_NORTH = 'KP',
  KOREA_SOUTH = 'KR',
  KUWAIT = 'KW',
  KYRGYZSTAN = 'KG',
  LAO = 'LA',
  LATVIA = 'LV',
  LEBANON = 'LB',
  LESOTHO = 'LS',
  LIBERIA = 'LR',
  LIBYA = 'LY',
  LIECHTENSTEIN = 'LI',
  LITHUANIA = 'LT',
  LUXEMBOURG = 'LU',
  MACAO = 'MO',
  MACEDONIA = 'MK',
  MADAGASCAR = 'MG',
  MALAWI = 'MW',
  MALAYSIA = 'MY',
  MALDIVES = 'MV',
  MALI = 'ML',
  MALTA = 'MT',
  MARSHALL_ISLANDS = 'MH',
  MARTINIQUE = 'MQ',
  MAURITANIA = 'MR',
  MAURITIUS = 'MU',
  MAYOTTE = 'YT',
  MEXICO = 'MX',
  MICRONESIA = 'FM',
  MOLDOVA = 'MD',
  MONACO = 'MC',
  MONGOLIA = 'MN',
  MONTENEGRO = 'ME',
  MONTSERRAT = 'MS',
  MOROCCO = 'MA',
  MOZAMBIQUE = 'MZ',
  MYANMAR = 'MM',
  NAMIBIA = 'NA',
  NAURU = 'NR',
  NEPAL = 'NP',
  NETHERLANDS = 'NL',
  NEW_CALEDONIA = 'NC',
  NEW_ZEALAND = 'NZ',
  NICARAGUA = 'NI',
  NIGER = 'NE',
  NIGERIA = 'NG',
  NIUE = 'NU',
  NORFOLK_ISLAND = 'NF',
  NORTHERN_MARIANA_ISLANDS = 'MP',
  NORWAY = 'NO',
  OMAN = 'OM',
  PAKISTAN = 'PK',
  PALAU = 'PW',
  PALESTINIAN_TERRITORY = 'PS',
  PANAMA = 'PA',
  PAPUA_NEW_GUINEA = 'PG',
  PARAGUAY = 'PY',
  PERU = 'PE',
  PHILIPPINES = 'PH',
  PITCAIRN = 'PN',
  POLAND = 'PL',
  PORTUGAL = 'PT',
  PUERTO_RICO = 'PR',
  QATAR = 'QA',
  RÉUNION = 'RE',
  ROMANIA = 'RO',
  RUSSIAN_FEDERATION = 'RU',
  RWANDA = 'RW',
  SAINT_BARTHÉLEMY = 'BL',
  SAINT_HELENA_ASCENSION_TRISTAN_DA_CUNHA = 'SH',
  SAINT_KITTS_NEVIS = 'KN',
  SAINT_LUCIA = 'LC',
  SAINT_MARTIN_FRENCH = 'MF',
  SAINT_PIERRE_MIQUELON = 'PM',
  SAINT_VINCENT_GRENADINES = 'VC',
  SAMOA = 'WS',
  SAN_MARINO = 'SM',
  SAO_TOME_PRINCIPE = 'ST',
  SAUDI_ARABIA = 'SA',
  SENEGAL = 'SN',
  SERBIA = 'RS',
  SEYCHELLES = 'SC',
  SIERRA_LEONE = 'SL',
  SINGAPORE = 'SG',
  SINT_MAARTEN = 'SX',
  SLOVAKIA = 'SK',
  SLOVENIA = 'SI',
  SOLOMON_ISLANDS = 'SB',
  SOMALIA = 'SO',
  SOUTH_AFRICA = 'ZA',
  SOUTH_GEORGIA_SANDWICH_ISLANDS = 'GS',
  SOUTH_SUDAN = 'SS',
  SPAIN = 'ES',
  SRI_LANKA = 'LK',
  SUDAN = 'SD',
  SURINAME = 'SR',
  SVALBARD_JAN_MAYEN = 'SJ',
  SWAZILAND = 'SZ',
  SWEDEN = 'SE',
  SWITZERLAND = 'CH',
  SYRIA = 'SY',
  TAIWAN = 'TW',
  TAJIKISTAN = 'TJ',
  TANZANIA = 'TZ',
  THAILAND = 'TH',
  TIMOR_LESTE = 'TL',
  TOGO = 'TG',
  TOKELAU = 'TK',
  TONGA = 'TO',
  TRINIDAD_TOBAGO = 'TT',
  TUNISIA = 'TN',
  TURKEY = 'TR',
  TURKMENISTAN = 'TM',
  TURKS_CAICOS_ISLANDS = 'TC',
  TUVALU = 'TV',
  UGANDA = 'UG',
  UKRAINE = 'UA',
  UNITED_ARAB_EMIRATES = 'AE',
  UNITED_KINGDOM = 'GB',
  UNITED_STATES = 'US',
  UNITED_STATES_OUTLYING_ISLANDS = 'UM',
  URUGUAY = 'UY',
  UZBEKISTAN = 'UZ',
  VANUATU = 'VU',
  VENEZUELA = 'VE',
  VIETNAM = 'VN',
  VIRGIN_ISLANDS_BRITISH = 'VG',
  VIRGIN_ISLANDS = 'VI',
  WALLIS_FUTUNA = 'WF',
  WESTERN_SAHARA = 'EH',
  YEMEN = 'YE',
  ZAMBIA = 'ZM',
  ZIMBABWE = 'ZW',
  USER_DEFINED = 'AA',
  KOSOVO = 'XK',
  INTERNATIONAL_WATERS = 'XZ',
  UNKNOWN = 'ZZ'
}

export const COUNTRY_NAME = {
  [Country.AFGHANISTAN]: 'Afghanistan',
  [Country.ALAND_ISLANDS]: 'Åland Islands',
  [Country.ALBANIA]: 'Albania',
  [Country.ALGERIA]: 'Algeria',
  [Country.AMERICAN_SAMOA]: 'American Samoa',
  [Country.ANDORRA]: 'Andorra',
  [Country.ANGOLA]: 'Angola',
  [Country.ANGUILLA]: 'Anguilla',
  [Country.ANTARCTICA]: 'Antarctica',
  [Country.ANTIGUA_BARBUDA]: 'Antigua and Barbuda',
  [Country.ARGENTINA]: 'Argentina',
  [Country.ARMENIA]: 'Armenia',
  [Country.ARUBA]: 'Aruba',
  [Country.AUSTRALIA]: 'Australia',
  [Country.AUSTRIA]: 'Austria',
  [Country.AZERBAIJAN]: 'Azerbaijan',
  [Country.BAHAMAS]: 'Bahamas',
  [Country.BAHRAIN]: 'Bahrain',
  [Country.BANGLADESH]: 'Bangladesh',
  [Country.BARBADOS]: 'Barbados',
  [Country.BELARUS]: 'Belarus',
  [Country.BELGIUM]: 'Belgium',
  [Country.BELIZE]: 'Belize',
  [Country.BENIN]: 'Benin',
  [Country.BERMUDA]: 'Bermuda',
  [Country.BHUTAN]: 'Bhutan',
  [Country.BOLIVIA]: 'Bolivia (Plurinational State of)',
  [Country.BONAIRE_SINT_EUSTATIUS_SABA]: 'Bonaire, Sint Eustatius and Saba',
  [Country.BOSNIA_HERZEGOVINA]: 'Bosnia and Herzegovina',
  [Country.BOTSWANA]: 'Botswana',
  [Country.BOUVET_ISLAND]: 'Bouvet Island',
  [Country.BRAZIL]: 'Brazil',
  [Country.BRITISH_INDIAN_OCEAN_TERRITORY]: 'British Indian Ocean Territory',
  [Country.BRUNEI_DARUSSALAM]: 'Brunei Darussalam',
  [Country.BULGARIA]: 'Bulgaria',
  [Country.BURKINA_FASO]: 'Burkina Faso',
  [Country.BURUNDI]: 'Burundi',
  [Country.CAMBODIA]: 'Cambodia',
  [Country.CAMEROON]: 'Cameroon',
  [Country.CANADA]: 'Canada',
  [Country.CAPE_VERDE]: 'Cabo Verde',
  [Country.CAYMAN_ISLANDS]: 'Cayman Islands',
  [Country.CENTRAL_AFRICAN_REPUBLIC]: 'Central African Republic',
  [Country.CHAD]: 'Chad',
  [Country.CHILE]: 'Chile',
  [Country.CHINA]: 'China',
  [Country.CHRISTMAS_ISLAND]: 'Christmas Island',
  [Country.COCOS_ISLANDS]: 'Cocos (Keeling) Islands',
  [Country.COLOMBIA]: 'Colombia',
  [Country.COMOROS]: 'Comoros',
  [Country.CONGO_DEMOCRATIC_REPUBLIC]: 'Congo, Democratic Republic of the',
  [Country.CONGO]: 'Congo',
  [Country.COOK_ISLANDS]: 'Cook Islands',
  [Country.COSTA_RICA]: 'Costa Rica',
  [Country.CÔTE_DIVOIRE]: 'Côte d’Ivoire',
  [Country.CROATIA]: 'Croatia',
  [Country.CUBA]: 'Cuba',
  [Country.CURAÇAO]: 'Curaçao',
  [Country.CYPRUS]: 'Cyprus',
  [Country.CZECH_REPUBLIC]: 'Czechia',
  [Country.DENMARK]: 'Denmark',
  [Country.DJIBOUTI]: 'Djibouti',
  [Country.DOMINICA]: 'Dominica',
  [Country.DOMINICAN_REPUBLIC]: 'Dominican Republic',
  [Country.ECUADOR]: 'Ecuador',
  [Country.EGYPT]: 'Egypt',
  [Country.EL_SALVADOR]: 'El Salvador',
  [Country.EQUATORIAL_GUINEA]: 'Equatorial Guinea',
  [Country.ERITREA]: 'Eritrea',
  [Country.ESTONIA]: 'Estonia',
  [Country.ETHIOPIA]: 'Ethiopia',
  [Country.FALKLAND_ISLANDS]: 'Falkland Islands (Malvinas)',
  [Country.FAROE_ISLANDS]: 'Faroe Islands',
  [Country.FIJI]: 'Fiji',
  [Country.FINLAND]: 'Finland',
  [Country.FRANCE]: 'France',
  [Country.FRENCH_GUIANA]: 'French Guiana',
  [Country.FRENCH_POLYNESIA]: 'French Polynesia',
  [Country.FRENCH_SOUTHERN_TERRITORIES]: 'French Southern Territories',
  [Country.GABON]: 'Gabon',
  [Country.GAMBIA]: 'Gambia',
  [Country.GEORGIA]: 'Georgia',
  [Country.GERMANY]: 'Germany',
  [Country.GHANA]: 'Ghana',
  [Country.GIBRALTAR]: 'Gibraltar',
  [Country.GREECE]: 'Greece',
  [Country.GREENLAND]: 'Greenland',
  [Country.GRENADA]: 'Grenada',
  [Country.GUADELOUPE]: 'Guadeloupe',
  [Country.GUAM]: 'Guam',
  [Country.GUATEMALA]: 'Guatemala',
  [Country.GUERNSEY]: 'Guernsey',
  [Country.GUINEA]: 'Guinea',
  [Country.GUINEA_BISSAU]: 'Guinea-Bissau',
  [Country.GUYANA]: 'Guyana',
  [Country.HAITI]: 'Haiti',
  [Country.HEARD_MCDONALD_ISLANDS]: 'Heard Island and McDonald Islands',
  [Country.VATICAN]: 'Holy See',
  [Country.HONDURAS]: 'Honduras',
  [Country.HONG_KONG]: 'Hong Kong',
  [Country.HUNGARY]: 'Hungary',
  [Country.ICELAND]: 'Iceland',
  [Country.INDIA]: 'India',
  [Country.INDONESIA]: 'Indonesia',
  [Country.IRAN]: 'Iran (Islamic Republic of)',
  [Country.IRAQ]: 'Iraq',
  [Country.IRELAND]: 'Ireland',
  [Country.ISLE_OF_MAN]: 'Isle of Man',
  [Country.ISRAEL]: 'Israel',
  [Country.ITALY]: 'Italy',
  [Country.JAMAICA]: 'Jamaica',
  [Country.JAPAN]: 'Japan',
  [Country.JERSEY]: 'Jersey',
  [Country.JORDAN]: 'Jordan',
  [Country.KAZAKHSTAN]: 'Kazakhstan',
  [Country.KENYA]: 'Kenya',
  [Country.KIRIBATI]: 'Kiribati',
  [Country.KOREA_NORTH]: 'Korea (Democratic People’s Republic of)',
  [Country.KOREA_SOUTH]: 'Korea, Republic of',
  [Country.KUWAIT]: 'Kuwait',
  [Country.KYRGYZSTAN]: 'Kyrgyzstan',
  [Country.LAO]: 'Lao People’s Democratic Republic',
  [Country.LATVIA]: 'Latvia',
  [Country.LEBANON]: 'Lebanon',
  [Country.LESOTHO]: 'Lesotho',
  [Country.LIBERIA]: 'Liberia',
  [Country.LIBYA]: 'Libya',
  [Country.LIECHTENSTEIN]: 'Liechtenstein',
  [Country.LITHUANIA]: 'Lithuania',
  [Country.LUXEMBOURG]: 'Luxembourg',
  [Country.MACAO]: 'Macao',
  [Country.MACEDONIA]: 'North Macedonia',
  [Country.MADAGASCAR]: 'Madagascar',
  [Country.MALAWI]: 'Malawi',
  [Country.MALAYSIA]: 'Malaysia',
  [Country.MALDIVES]: 'Maldives',
  [Country.MALI]: 'Mali',
  [Country.MALTA]: 'Malta',
  [Country.MARSHALL_ISLANDS]: 'Marshall Islands',
  [Country.MARTINIQUE]: 'Martinique',
  [Country.MAURITANIA]: 'Mauritania',
  [Country.MAURITIUS]: 'Mauritius',
  [Country.MAYOTTE]: 'Mayotte',
  [Country.MEXICO]: 'Mexico',
  [Country.MICRONESIA]: 'Micronesia (Federated States of)',
  [Country.MOLDOVA]: 'Moldova, Republic of',
  [Country.MONACO]: 'Monaco',
  [Country.MONGOLIA]: 'Mongolia',
  [Country.MONTENEGRO]: 'Montenegro',
  [Country.MONTSERRAT]: 'Montserrat',
  [Country.MOROCCO]: 'Morocco',
  [Country.MOZAMBIQUE]: 'Mozambique',
  [Country.MYANMAR]: 'Myanmar',
  [Country.NAMIBIA]: 'Namibia',
  [Country.NAURU]: 'Nauru',
  [Country.NEPAL]: 'Nepal',
  [Country.NETHERLANDS]: 'Netherlands',
  [Country.NEW_CALEDONIA]: 'New Caledonia',
  [Country.NEW_ZEALAND]: 'New Zealand',
  [Country.NICARAGUA]: 'Nicaragua',
  [Country.NIGER]: 'Niger',
  [Country.NIGERIA]: 'Nigeria',
  [Country.NIUE]: 'Niue',
  [Country.NORFOLK_ISLAND]: 'Norfolk Island',
  [Country.NORTHERN_MARIANA_ISLANDS]: 'Northern Mariana Islands',
  [Country.NORWAY]: 'Norway',
  [Country.OMAN]: 'Oman',
  [Country.PAKISTAN]: 'Pakistan',
  [Country.PALAU]: 'Palau',
  [Country.PALESTINIAN_TERRITORY]: 'Palestine, State of',
  [Country.PANAMA]: 'Panama',
  [Country.PAPUA_NEW_GUINEA]: 'Papua New Guinea',
  [Country.PARAGUAY]: 'Paraguay',
  [Country.PERU]: 'Peru',
  [Country.PHILIPPINES]: 'Philippines',
  [Country.PITCAIRN]: 'Pitcairn',
  [Country.POLAND]: 'Poland',
  [Country.PORTUGAL]: 'Portugal',
  [Country.PUERTO_RICO]: 'Puerto Rico',
  [Country.QATAR]: 'Qatar',
  [Country.RÉUNION]: 'Réunion',
  [Country.ROMANIA]: 'Romania',
  [Country.RUSSIAN_FEDERATION]: 'Russian Federation',
  [Country.RWANDA]: 'Rwanda',
  [Country.SAINT_BARTHÉLEMY]: 'Saint Barthélemy',
  [Country.SAINT_HELENA_ASCENSION_TRISTAN_DA_CUNHA]:
    'Saint Helena, Ascension and Tristan da Cunha',
  [Country.SAINT_KITTS_NEVIS]: 'Saint Kitts and Nevis',
  [Country.SAINT_LUCIA]: 'Saint Lucia',
  [Country.SAINT_MARTIN_FRENCH]: 'Saint Martin (French part)',
  [Country.SAINT_PIERRE_MIQUELON]: 'Saint Pierre and Miquelon',
  [Country.SAINT_VINCENT_GRENADINES]: 'Saint Vincent and the Grenadines',
  [Country.SAMOA]: 'Samoa',
  [Country.SAN_MARINO]: 'San Marino',
  [Country.SAO_TOME_PRINCIPE]: 'Sao Tome and Principe',
  [Country.SAUDI_ARABIA]: 'Saudi Arabia',
  [Country.SENEGAL]: 'Senegal',
  [Country.SERBIA]: 'Serbia',
  [Country.SEYCHELLES]: 'Seychelles',
  [Country.SIERRA_LEONE]: 'Sierra Leone',
  [Country.SINGAPORE]: 'Singapore',
  [Country.SINT_MAARTEN]: 'Sint Maarten (Dutch part)',
  [Country.SLOVAKIA]: 'Slovakia',
  [Country.SLOVENIA]: 'Slovenia',
  [Country.SOLOMON_ISLANDS]: 'Solomon Islands',
  [Country.SOMALIA]: 'Somalia',
  [Country.SOUTH_AFRICA]: 'South Africa',
  [Country.SOUTH_GEORGIA_SANDWICH_ISLANDS]:
    'South Georgia and the South Sandwich Islands',
  [Country.SOUTH_SUDAN]: 'South Sudan',
  [Country.SPAIN]: 'Spain',
  [Country.SRI_LANKA]: 'Sri Lanka',
  [Country.SUDAN]: 'Sudan',
  [Country.SURINAME]: 'Suriname',
  [Country.SVALBARD_JAN_MAYEN]: 'Svalbard and Jan Mayen',
  [Country.SWAZILAND]: 'Eswatini',
  [Country.SWEDEN]: 'Sweden',
  [Country.SWITZERLAND]: 'Switzerland',
  [Country.SYRIA]: 'Syrian Arab Republic',
  [Country.TAIWAN]: 'Chinese Taipei',
  [Country.TAJIKISTAN]: 'Tajikistan',
  [Country.TANZANIA]: 'Tanzania, United Republic of',
  [Country.THAILAND]: 'Thailand',
  [Country.TIMOR_LESTE]: 'Timor-Leste',
  [Country.TOGO]: 'Togo',
  [Country.TOKELAU]: 'Tokelau',
  [Country.TONGA]: 'Tonga',
  [Country.TRINIDAD_TOBAGO]: 'Trinidad and Tobago',
  [Country.TUNISIA]: 'Tunisia',
  [Country.TURKEY]: 'Turkey',
  [Country.TURKMENISTAN]: 'Turkmenistan',
  [Country.TURKS_CAICOS_ISLANDS]: 'Turks and Caicos Islands',
  [Country.TUVALU]: 'Tuvalu',
  [Country.UGANDA]: 'Uganda',
  [Country.UKRAINE]: 'Ukraine',
  [Country.UNITED_ARAB_EMIRATES]: 'United Arab Emirates',
  [Country.UNITED_KINGDOM]:
    'United Kingdom of Great Britain and Northern Ireland',
  [Country.UNITED_STATES]: 'United States of America',
  [Country.UNITED_STATES_OUTLYING_ISLANDS]:
    'United States Minor Outlying Islands',
  [Country.URUGUAY]: 'Uruguay',
  [Country.UZBEKISTAN]: 'Uzbekistan',
  [Country.VANUATU]: 'Vanuatu',
  [Country.VENEZUELA]: 'Venezuela (Bolivarian Republic of)',
  [Country.VIETNAM]: 'Viet Nam',
  [Country.VIRGIN_ISLANDS_BRITISH]: 'Virgin Islands (British)',
  [Country.VIRGIN_ISLANDS]: 'Virgin Islands (U.S.)',
  [Country.WALLIS_FUTUNA]: 'Wallis and Futuna',
  [Country.WESTERN_SAHARA]: 'Western Sahara',
  [Country.YEMEN]: 'Yemen',
  [Country.ZAMBIA]: 'Zambia',
  [Country.ZIMBABWE]: 'Zimbabwe',
  [Country.USER_DEFINED]: 'user defined',
  [Country.KOSOVO]: 'Kosovo',
  [Country.INTERNATIONAL_WATERS]: 'international waters',
  [Country.UNKNOWN]: 'unknown or invalid'
}
